---
- name: Compress and Move directory to destination
  hosts: virtualmachines
  #hosts: localhost
  #connection: local
  
  tasks:
  - name: Clone of main branch including solution for the callenge given to Benjamin Bollhalter from SNB
    ansible.builtin.git:
      repo: https://github.com/21staff/Challenge.git
      dest: /tmp/challenge/repo
      single_branch: yes
      version: main
      
  - name: Compress directory /tmp/challenge/repo/ into /tmp/challenge/Bollhalter_Benjamin_Challenge_14.04.2023.tgz
    community.general.archive:
      path: /tmp/challenge/repo/
      dest: /tmp/challenge/Bollhalter_Benjamin_Challenge_14.04.2023.tgz

  - name: Copy file with owner and permission, using symbolic representation
    ansible.builtin.copy:
      src: /tmp/challenge/Bollhalter_Benjamin_Challenge_14.04.2023.tgz
      dest: /media/agent/portable/Bollhalter_Benjamin_Challenge_14.04.2023.tgz
      remote_src: true
      
  - name: Remove temporary file (delete file)
    ansible.builtin.file:
      path: /tmp/challenge/Bollhalter_Benjamin_Challenge_14.04.2023.tgz
      state: absent
      
  - name: Recursively remove git directory
    ansible.builtin.file:
      path: /tmp/challenge
      state: absent
