---
- name: Copress and Move directory to destination
  #hosts: webservers
  #remote_user: agent
  hosts: localhost
  connection: local
  
  tasks:
  - name: Compress directory /home/agent/Documents/Challenge/source/ into /home/agent/Documents/Challenge/source/arcived_source.tgz
    community.general.archive:
      path: /home/agent/Documents/Challenge/source/
      dest: /home/agent/Documents/Challenge/source/arcived_source.tgz

  - name: Copy file with owner and permission, using symbolic representation
    ansible.builtin.copy:
      src: /home/agent/Documents/Challenge/source/arcived_source.tgz
      dest: /media/agent/portable/arcived_source.tgz
      owner: agent
     # group: users #Run 'compgen -g' to list user groups
      mode: u=rw,g=r,o=r
